### ISSUE TITLE
More subtitle languages support

### ISSUE THREAD

**Issue by Michelangelo1337** [Deathspike/animesync#15]
Consider this please as a feature request. Adding a parameter such as --defSub to set one subtitle language as a default language while muxing to mkv would be also awesone

**Comment by Deathspike** [comment]
This is something I definitely want to add in the future. This requires the following features:

- [ ] Extend ffmpeg call with multiple subtitles and metadata. Refer to https://github.com/Deathspike/animesync/commit/7559a10a2edf1692c0744e66bc5379abdd4cc954. This commit breaks the multi-subtitle support that was in place (exclusive to CrunchyRoll). This is because ffmpeg auto-detection does not work when passing in a m3u8 with multiple resolutions *and* multiple subtitle files. So `animesync` will have to decide on the quality of the m3u8 stream to select (default 1080p for now) and pass that to ffmpeg. This requires parsing of m3u8 and that will come in a future update which also allows `animesync` to serve m3u8 streams directly to external players (e.g. VLC).
- [ ] Extend CrunchyRoll support for multi-subtitles. This is already in the aforementioned commit, so a non-issue really.
- [ ] Extend Funimation support for multi-subtitles. If someone can figure out where the subtitle info is stored, that would help!

This feature relates to #14. Notes mostly as self-reminders, but info sharing is definitely appreciated.

**Comment by Michelangelo1337** [comment]
Great! As far as I know Funimation does not offer multi-subtitles. Thanks for the hard work!

**Comment by Deathspike** [comment]
No prob! The series [By the Grace of the Gods](https://www.funimation.com/shows/by-the-grace-of-the-gods/ryoma-with-the-slimes/?qid=undefined&lang=japanese) does have multiple languages. It has the following:

* English
* Spanish (Latin Am)
* Portuguese (Brazil)

That said, Funimation multi-subtitle can always be added later. CrunchyRoll has the bigger focus on non-English markets.

**Comment by Michelangelo1337** [comment]
That must be new! but y it would be a good idea to add the support to crunchyroll first. Adding filename template and server selection for better downloads could also be good ideas.

**Comment by Deathspike** [comment]
I've been thinking about this feature. Setting a default subtitle language makes no sense for `animesync`. It changes the way a file is output based on user preferences and that's not what should be desired. The output routine should be predictable and consistent, independent of user preferences. That's why audio language should always default to JPN and subtitles always to ENG. If you prefer a different audio or subtitle language, you can configure your video player to automatically select it. So there will be no `--defSub`.

As for filename template and server selection, please make a new issue to elaborate. It doesn't sound appealing or desired with the information that I have right now.

**Comment by Deathspike** [comment]
Fixed in `.0.7.0` 👍
